name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: xcodebuild test -project Test-Automation-With-GitHub-Actions-240815.xcodeproj/ -scheme Test-Automation-With-GitHub-Actions-240815 -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15"
        
